version: '3.7'
services:
  db:
    image: postgres:12.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: local_todo_db
    ports:
      - "5432:5432"
        
  todo-api:
    build:
        context: ../../
        dockerfile: deploy/local/Dockerfile
    restart: unless-stopped
    environment:
      ENV: development
      APP_PORT: 8080
      ALLOWED_HOSTS: "*"
      DB_DRIVER: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: username
      DB_PASSWORD: password
      DB_NAME: local_todo_db
      DB_SSL_MODE: disable
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:8080"