apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-api-prod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  project: prod-project
  source:
    helm:
      valueFiles:
        - argocd/services/todo/base/envs/prod.yaml
    path: argocd/services/todo/base
    repoURL: https://github.com/pedromspeixoto/k8s-stack.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true