apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-api-staging
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  project: staging-project
  source:
    helm:
      valueFiles:
        - ../envs/staging.yaml
    path: argocd/services/todo/base
    repoURL: https://github.com/pedromspeixoto/k8s-stack.git
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true