image:
  tag: master
env:
  ENV: prod
  APP_PORT: 8080
  ALLOWED_HOSTS: "*"
  GIN_RELEASE: release
  DB_DRIVER: postgres
  DB_HOST: postgresql-prod.services.svc.cluster.local
  DB_PORT: 5432
  DB_USER: username
  DB_PASSWORD: password
  DB_NAME: postgres
  DB_SSL_MODE: disable
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
autoscaling:
  minScale: 1
  maxScale: 10