image:
  tag: b26aa2cd30055fc89d288ae998a8fc4e4d011d2f
env:
  ENV: staging
  APP_PORT: "8080"
  ALLOWED_HOSTS: "*"
  DB_DRIVER: postgres
  DB_HOST: postgresql-staging.staging.svc.cluster.local
  DB_PORT: "5432"
  DB_USER: username
  DB_PASSWORD: password
  DB_NAME: staging_todo_db
  DB_SSL_MODE: disable
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
autoscaling:
  minScale: 1
  maxScale: 10